# Create your Kivy layout in the kv language here
BoxLayout:
    orientation: 'horizontal'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Sort by:'
            font_size: 30

#        Spinner:
#            id: sort_by
#            text: 'Work in progress'
        Label:
            text: 'Name'
        TextInput:
            id: name_input
        TextInput:
            id: country_input
        TextInput:
            id: priority_input
        Button:


